-- Listing 7.14 Get a list of tables and views
SET search_path = Item44Example;

SELECT T.TABLE_NAME, T.TABLE_TYPE, T.TABLE_SCHEMA
FROM INFORMATION_SCHEMA.TABLES AS T
WHERE T.TABLE_SCHEMA = 'item44example'
  AND T.TABLE_TYPE IN ('BASE TABLE', 'VIEW');